---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-kub
spec:
  template:
    metadata:
      labels:
	tag: label-kub
    spec:
      containers:
      - name: ctr
        image: nginx
  replicas: 1
  selector:
      matchLables:
        tag: label-kub
